# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComment', models.IntegerField(unique=True)),
                ('Course', models.TextField(max_length=255)),
                ('Text', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCourse', models.IntegerField(unique=True)),
                ('Name', models.TextField(max_length=255)),
                ('Duration', models.TextField(max_length=255)),
                ('Teacher', models.TextField(max_length=255)),
                ('Value', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUser', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('bill', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
    ]
