# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20161229_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='idComment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='idCourse',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idUser',
        ),
    ]
