# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20161231_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Picture',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
