# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='users.Course'),
        ),
    ]
