# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170104_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='users', to='users.Course'),
        ),
    ]
