# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Useri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(default=b'login', max_length=255)),
                ('password', models.CharField(default=b'12345', max_length=255)),
                ('Phone_number', models.CharField(max_length=255, null=True)),
                ('courses', models.ManyToManyField(related_name='toi', to='users.Course')),
            ],
        ),
    ]
